import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

class EndScreen extends StatelessWidget {
  EndScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 420 ,
      height: 310,
      padding: EdgeInsets.fromLTRB(0, 20, 0, 0),
      decoration: BoxDecoration(
        color: Color(0xFF333333),
      ),
      child: Column(
        children: [
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Column(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  TextButton(onPressed: (){},
                    child: Text('Instagram',
                      style: GoogleFonts.getFont('Epilogue',
                        fontWeight: FontWeight.w300,
                        fontSize: 16,
                        height: 1.3,
                        color: Color(0xFFFCFCFC),
                      ),
                    ),
                  ),
                  TextButton(onPressed: (){},
                    child: Text('Twitter',
                      style: GoogleFonts.getFont('Epilogue',
                        fontWeight: FontWeight.w300,
                        fontSize: 16,
                        height: 1.3,
                        color: Color(0xFFFCFCFC),
                      ),
                    ),
                  ),
                  TextButton(onPressed: (){},
                    child: Text('Discord',
                      style: GoogleFonts.getFont('Epilogue',
                        fontWeight: FontWeight.w300,
                        fontSize: 16,
                        height: 1.3,
                        color: Color(0xFFFCFCFC),
                      ),
                    ),
                  ),
                  TextButton(onPressed: (){},
                    child: Text('Blog',
                      style: GoogleFonts.getFont('Epilogue',
                        fontWeight: FontWeight.w300,
                        fontSize: 16,
                        height: 1.3,
                        color: Color(0xFFFCFCFC),
                      ),
                    ),
                  ),
                ],
              ),
              Column(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  TextButton(onPressed: (){},
                    child: Text('About',
                      style: GoogleFonts.getFont('Epilogue',
                        fontWeight: FontWeight.w300,
                        fontSize: 16,
                        height: 1.3,
                        color: Color(0xFFFCFCFC),
                      ),
                    ),
                  ),
                  TextButton(onPressed: (){},
                    child: Text('Community Guidelines',
                      style: GoogleFonts.getFont('Epilogue',
                        fontWeight: FontWeight.w300,
                        fontSize: 16,
                        height: 1.3,
                        color: Color(0xFFFCFCFC),
                      ),
                    ),
                  ),
                  TextButton(onPressed: (){},
                    child: Text('Terms of Service',
                      style: GoogleFonts.getFont('Epilogue',
                        fontWeight: FontWeight.w300,
                        fontSize: 16,
                        height: 1.3,
                        color: Color(0xFFFCFCFC),
                      ),
                    ),
                  ),
                  TextButton(onPressed: (){},
                    child: Text('Privacy',
                      style: GoogleFonts.getFont('Epilogue',
                        fontWeight: FontWeight.w300,
                        fontSize: 16,
                        height: 1.3,
                        color: Color(0xFFFCFCFC),
                      ),
                    ),
                  ),
                  TextButton(onPressed: (){},
                    child: Text('Careers',
                      style: GoogleFonts.getFont('Epilogue',
                        fontWeight: FontWeight.w300,
                        fontSize: 16,
                        height: 1.3,
                        color: Color(0xFFFCFCFC),
                      ),
                    ),
                  ),
                  TextButton(onPressed: (){},
                    child: Text('Help',
                      style: GoogleFonts.getFont('Epilogue',
                        fontWeight: FontWeight.w300,
                        fontSize: 16,
                        height: 1.3,
                        color: Color(0xFFFCFCFC),
                      ),
                    ),
                  ),
                ],
              ),
            ],
          ),
          SizedBox(height: 10,),
          Container(
            margin: EdgeInsets.fromLTRB(0, 0, 0, 0),
            decoration: BoxDecoration(
              color: Color(0xFFDCDCDC),
            ),
            child: Container(
              width: 410,
              height: 1,
            ),
          ),
          Container(
            margin: EdgeInsets.fromLTRB(0, 20, 260, 20),
            padding: EdgeInsets.only(top: 15), //EdgeInsets.fromLTRB(0, 15, 0, 0),
            child: Text('© 2021 Openart',
              style: GoogleFonts.getFont('Epilogue',
                fontWeight: FontWeight.w300,
                fontSize: 13,
                height: 1.3,
                color: Color(0xFFFCFCFC),
              ),
            ),
          ),
        ],
      ),
    );
  }
}